"""Authored A2 Spanish cues for stable quizzes, independent of model output.

Order follows the verified textbook glossary in a2_sample. These are original
explanations, not quotations. Shared forms keep their category-specific sense.
"""
from .a2_sample import WORDS, GROUPS

CLUE_GROUPS = {
    'Animales': 'Animal pequeño con una cola larga que sube a los árboles y come frutos secos.|Animal grande que una persona puede montar.|Animal del mar que respira aire y suele saltar fuera del agua.|Animal grande de pelo espeso que puede vivir en el bosque.',
    'Comida': 'Comer por la mañana, al empezar el día.|Tomar alimentos, por ejemplo al mediodía.|Comer por la noche.|Alimento que viene de animales, como el pollo.|Alimento con mucho azúcar, como un caramelo.|Alimento como una manzana, una naranja o un plátano.',
    'Tiempo libre': 'Moverse con las piernas más rápido que al caminar.|Encontrarse dentro del lugar donde vives.|Empezar una relación de amistad con otras personas.|Mover el cuerpo para estar sano, por ejemplo nadar o jugar al tenis.|Decidir qué actividades quieres realizar después.|Practicar idiomas con otra persona y ayudaros con vuestros idiomas.|Practicar posiciones del cuerpo y respirar con calma.|Visitar tiendas para comprar cosas.|Viajar o descansar durante unos días sin trabajar.|Practicar un deporte de equipo con un balón y dos porterías.|Divertirse con juegos en una consola o un ordenador.|Seguir y entender las palabras de una novela u otra obra escrita.|Dedicar parte del día a actividades dentro de tu vivienda.|Mejorar el estado físico del cuerpo con ejercicio.|Acordar el momento del día para encontrarse con alguien.|Encontrarse con personas con las que tienes amistad.|Descansar y dejar de estar nervioso.|Ir a bares, al cine u otros lugares cuando ya es de noche.|Estar bajo la luz del sol para disfrutar de ella.|Beber una bebida oscura que suele ayudar a despertarse.|Mirar historias de cine en una pantalla.|Mirar historias divididas en episodios en la televisión u otra pantalla.',
    'Intereses': 'Actividades creativas como pintar o hacer esculturas.|El mundo de las películas y de las salas donde se ven.|Lo que preparamos y tomamos para alimentarnos.|Las costumbres, ideas y formas de vivir de una sociedad.|Actividad física con reglas, como el tenis.|El estudio de lo que pasó en otras épocas.|Las formas de vestir que son populares en un momento.|El arte de combinar sonidos, por ejemplo en una canción.|Los animales, las plantas, los ríos y otros elementos del mundo no creados por personas.|Herramientas y conocimientos para crear aparatos y resolver problemas, como los ordenadores.',
    'Ropa': 'Prenda larga y gruesa que llevas encima de la ropa cuando hace frío.|Prenda sencilla para la parte superior del cuerpo, a menudo de manga corta.|Conjunto de chaqueta y pantalón que se lleva en ocasiones formales.|Pantalones de tela fuerte, normalmente de color azul.',
    'Carácter': 'Una persona que acepta nuevas ideas y habla con facilidad con otras personas.|Una persona que suele estar contenta y mostrar buen humor.|Una persona que quiere conseguir mucho y llegar lejos.|Una persona que prefiere pasar tiempo en su vivienda.|Una persona que conoce y acepta formas de vida de muchos países.|Una persona a la que le gusta mucho la actividad física.|Una persona con energía, activa y con ganas de hacer cosas.|Una persona con la que lo pasas bien y te ríes.|Una persona que comparte lo que tiene y ayuda a los demás.|Una persona que prefiere actuar por su cuenta y pensar en sus propios intereses.|Una persona inquieta a la que le cuesta estar en calma.|Una persona con pocas ganas de trabajar o hacer esfuerzos.|Una persona que suele ver el lado bueno de las cosas.|Una persona sin tensión, que se toma las cosas con calma.|Una persona que disfruta hablando y pasando tiempo con otras personas.|Una persona a la que le da vergüenza hablar con gente nueva.|Una persona que actúa con calma y no se altera fácilmente.|Una persona que evita trabajar o hacer esfuerzos.|Alguien que trata bien a los demás y actúa con bondad.',
    'Redes sociales': 'Inscribirse para participar en una reunión o actividad organizada.|Dar a otras personas la información de una actividad organizada.|Pasar con otras personas los momentos en que no tienes obligaciones.|Encontrarse y empezar a tratar con personas nuevas.|Organizar una actividad a la que pueden apuntarse otras personas.|Publicar un mensaje en la página personal de una red social.|Empezar una relación de amistad con otras personas.|Reunir a varias personas para realizar algo juntas.|Mostrar interés romántico por alguien e intentar atraerle.|Elegir a una persona que participa en un juego mediante un voto.|Programa que usas en un móvil u ordenador.|Forma corta de llamar a un programa para el móvil.|Actividad o reunión organizada a la que asiste gente.|Página donde una persona presenta quién es en una red social.|Espacio de una red social donde se publican mensajes.',
    'En la escuela de español': 'Usar bien los minutos y las horas que tienes disponibles.|Inscribirse para participar en algo organizado.|Ir a una clase, un taller u otra propuesta organizada.|Dar apoyo a las personas que estudian contigo.|Empezar a tratar con más personas que están aprendiendo.|Encontrar qué quiere decir una palabra o una expresión.|Comprender la información sobre lo que pasa en el mundo.|Preparar mensajes escritos para enviarlos a otras personas.|Oír a alguien pensando bien en lo que dice.|Realizar actividades fuera de los edificios.|Realizar actividades con las que lo pasas bien.|Completar en casa las tareas que te manda el profesor.|Practicar idiomas con otra persona y ayudaros con vuestros idiomas.|Seguir y entender las palabras de una novela u otra obra escrita.|Aprender a decir los sonidos y las palabras de forma más clara.|Decir lo que piensas sobre un tema.|Usar una lengua para aprender a hablarla mejor.|Poder recuperar en la memoria las palabras que has aprendido.|Tener ganas de descubrir y saber más.|No estar seguro de algo y necesitar una explicación.|Poder hablar con continuidad, sin parar mucho para buscar palabras.|Colaborar con otras personas para realizar una tarea.|Expresar en otra lengua lo que dice un texto.|Ejercicio o juego que sirve para aprender de forma divertida.|Lugar donde puedes consultar o pedir prestados libros.|Lugar donde puedes tomar bebidas y algo de comer.|Historia contada con dibujos y palabras.|Narración breve, a menudo inventada.|Persona que sabe mucho sobre un tema.|Reglas que explican cómo se forman y se combinan las palabras.|Narración de unos hechos, reales o inventados.|Lugar acordado para reunirse con otras personas.|Lugar de entrada donde atienden e informan a los visitantes.|Narración de algo que ha sucedido o que alguien imagina.|Actividad práctica en grupo para aprender a redactar textos.|Asunto del que hablan dos o más personas.|La manera de decir los sonidos de una lengua.|El conjunto de palabras que conoces o estudias.',
    'En la ciudad': 'Pagar para usar una bicicleta durante un tiempo.|Desplazarse en bicicleta.|Visitar las calles de la parte más vieja de una ciudad.|Obra pintada que se puede colgar en una pared.|Edificio donde se muestran obras de arte u objetos de interés.|Zona con árboles y caminos donde puedes pasear y descansar.|Construcción que permite pasar sobre un río o una carretera.|Corriente de agua que recorre la tierra.|Lugar por donde sales de una estación de transporte subterráneo.|Acción de ir a un lugar para conocerlo o ver a alguien.',
    'Para preguntar': 'Preguntas para saber cómo expresar una idea o escribir una palabra.|Pregunta para saber si hay que poner un acento escrito.|Pides a otra persona que te dé ayuda.|Pides que alguien vuelva a decir algo.|Preguntas por las palabras que otra persona acaba de decir.|Preguntas por el sentido de una palabra o expresión.|Preguntas por el sentido de algo que no entiendes.',
}

CLUES = {}
for group_index, (category, items) in enumerate(GROUPS.items()):
    clues = CLUE_GROUPS[category].split('|')
    assert len(clues) == len(items.split(';')), category
    CLUES.update({f'{group_index}-{i}': clue for i, clue in enumerate(clues)})

BY_ID = {word['id']: {**word, 'clue': CLUES[word['id']]} for word in WORDS}

# A personal introduction becomes a social encounter, then a learning plan.
ORDER = ['Carácter', 'Intereses', 'Tiempo libre', 'Comida', 'Ropa', 'Animales',
         'Redes sociales', 'Para preguntar', 'En la escuela de español', 'En la ciudad']
TITLES = ['Así soy', 'Lo que me interesa', 'Mis ratos libres', 'A la mesa',
          'Mi estilo', 'Animales y personalidad', 'Conocer gente', 'Pedir ayuda',
          'Aprender juntos', 'Explorar la ciudad']
CHAPTERS = []
for category, title in zip(ORDER, TITLES):
    ids = [word['id'] for word in WORDS if word['category'] == category]
    for start in range(0, len(ids), 5):
        CHAPTERS.append({'title': title, 'category': category, 'words': ids[start:start + 5]})
