"""Distinct real-life role-play scenarios for every curriculum unit."""


def _s(role: str, scene: str, opening: str, prompts: list[str], closing: str) -> dict:
    return {"role": role, "scene": scene, "opening": opening, "prompts": prompts, "closing": closing}


CONVERSATION_SCENARIOS = {
    "En el café": _s("camarera", "Pedir en una cafetería", "Buenos días. ¿Qué vas a tomar?", ["Claro. ¿Quieres algo para comer?", "Perfecto. ¿Lo tomas aquí o en la terraza?", "Son cinco euros. ¿Pagas en efectivo o con tarjeta?"], "Gracias. Aquí tienes tu pedido. ¡Que aproveche!"),
    "Primeras presentaciones": _s("nueva compañera", "Conocerse el primer día", "Hola, soy Ana. ¿Cómo te llamas y de dónde eres?", ["Encantada. ¿Dónde vives ahora?", "¿Qué idiomas hablas?", "¿Qué te gusta hacer en tu tiempo libre?"], "Me ha encantado conocerte. Nos vemos en clase."),
    "Mi familia y mi casa": _s("amiga", "Enseñar fotos de casa y familia", "¿Quién aparece contigo en esta foto?", ["¿Cómo es esa persona?", "¿Vivís juntos? Describe vuestra casa.", "¿Cuál es tu habitación favorita y por qué?"], "Gracias por enseñarme tu familia y tu casa."),
    "Un día normal": _s("compañera", "Comparar rutinas", "¿A qué hora te levantas normalmente?", ["¿Qué haces después de desayunar?", "¿Cómo vas al trabajo o a clase?", "¿Qué haces antes de acostarte?"], "Tenemos rutinas diferentes, pero las dos son interesantes."),
    "Aprender juntos": _s("compañera de español", "Organizar una sesión de estudio", "¿Qué parte del español te resulta más difícil?", ["¿Cómo practicas esa parte normalmente?", "¿Quieres practicar conmigo esta semana?", "¿Qué día y a qué hora te viene bien?"], "Perfecto. Estudiaremos juntos y hablaremos solo en español."),
    "A1 · Unidad 6: Esto me gusta": _s("amiga", "Descubrir gustos comunes", "¿Qué te gusta hacer en tu tiempo libre?", ["A mí también me gusta. ¿Con quién lo haces?", "¿Qué actividad no te gusta nada?", "¿Quieres hacer algo juntos este viernes?"], "Ya tenemos un buen plan para compartir nuestros gustos."),
    "A1 · Unidad 7: De aquí para allá": _s("persona del barrio", "Pedir indicaciones", "Hola, pareces un poco perdido. ¿Qué lugar buscas?", ["Está cerca. ¿Prefieres ir a pie o en metro?", "¿Desde qué calle vienes?", "¿Quieres que te explique la ruta otra vez?"], "Sigue todo recto y gira a la derecha. ¡Buen paseo!"),
    "A1 · Unidad 8: ¿Qué hacemos?": _s("amiga", "Hacer planes para el sábado", "¿Estás libre el sábado por la tarde?", ["¿Prefieres tomar tapas o ir al cine?", "¿Dónde podemos quedar?", "¿A qué hora te viene bien?"], "Genial, entonces tenemos plan para el sábado."),
    "A1 · Unidad 9: Tiempo y ropa": _s("amiga", "Elegir ropa según el tiempo", "Mira por la ventana. ¿Qué tiempo hace hoy?", ["¿Qué ropa vas a ponerte?", "¿De qué color es tu prenda favorita?", "¿Necesitamos paraguas o gafas de sol?"], "Perfecto, ya estamos preparados para salir."),
    "A1 · Unidad 10: Ciudadanos del mundo": _s("compañera de viaje", "Compartir experiencias", "¿Has viajado alguna vez a otro país?", ["¿Qué lugar has visitado?", "¿Qué sabes hacer que aprendiste allí?", "¿Qué país quieres conocer después?"], "Qué buenas experiencias. Ojalá hagamos otro viaje pronto."),
    "Charla con vecinos": _s("vecina", "Organizar un encuentro vecinal", "¿Qué planes tienes para este fin de semana?", ["Estamos organizando una comida. ¿Te apetece venir?", "¿Qué podrías traer para compartir?", "¿Te viene bien el domingo a las dos?"], "Estupendo, contaré contigo para la comida de vecinos."),
    "De viaje": _s("empleada de información", "Resolver un trayecto en la estación", "Buenos días. ¿Adónde quiere viajar?", ["¿Prefiere billete de ida o de ida y vuelta?", "Hay un tren directo y otro con escala. ¿Cuál prefiere?", "¿Va a facturar equipaje o lleva solo una maleta pequeña?"], "Aquí tiene su billete. La puerta de embarque aparece en la pantalla."),
    "Compras en el mercado": _s("vendedora", "Comprar productos frescos", "Buenos días. ¿Qué le pongo?", ["¿Cuánto quiere: un kilo o medio kilo?", "También tenemos fruta madura. ¿Quiere probarla?", "Son ocho euros. ¿Necesita una bolsa?"], "Muchas gracias. Que disfrute de los productos del mercado."),
    "En la consulta": _s("médica", "Explicar un problema de salud", "Buenos días. ¿Qué le pasa?", ["¿Desde cuándo tiene esos síntomas?", "¿Tiene fiebre o dolor de garganta?", "Debe descansar y tomar esta medicina. ¿Tiene alguna pregunta?"], "Cuídese y vuelva si no se encuentra mejor en tres días."),
    "Buscar piso": _s("agente inmobiliaria", "Preguntar por un piso", "Hola. ¿Qué tipo de piso está buscando?", ["¿Cuántos dormitorios necesita?", "El alquiler incluye los gastos. ¿Qué más quiere saber?", "¿Le gustaría concertar una visita mañana?"], "Perfecto, le espero mañana para visitar el piso."),
    "Vitamina A2 · U1: Vamos a conocernos": _s("compañera nueva", "Conocer a alguien del grupo", "¿Qué te gusta hacer en tu tiempo libre?", ["¿Qué actividad sueles hacer durante la semana?", "¿Qué te cuesta más cuando aprendes español?", "¿Qué podríamos practicar juntos?"], "Tenemos intereses parecidos; seguro que aprenderemos mucho juntos."),
    "Vitamina A2 · U2: Mi lugar en el mundo": _s("vecina expatriada", "Comparar lugares donde vivir", "¿Prefieres vivir en la ciudad o en el campo?", ["¿Qué servicios son importantes para ti?", "¿Qué fue lo más difícil cuando llegaste aquí?", "¿Qué consejo darías a una persona recién llegada?"], "Gracias. Tus consejos ayudarán a otras personas a sentirse en casa."),
    "Vitamina A2 · Repaso U1–U2": _s("compañera de clase", "Repasar gustos y rutinas", "Preséntate y cuéntame algo que te guste mucho.", ["¿Cómo es un día normal para ti?", "¿Qué parte del español te cuesta y cómo la practicas?", "¿Prefieres tu barrio o el centro de la ciudad? Explica por qué."], "Buen repaso: has hablado de ti, de tu rutina y de tu entorno."),
    "Una ruta de senderismo": _s("organizadora de excursiones", "Preparar una ruta", "Estamos preparando una ruta el domingo. ¿Te apetece venir?", ["Quedamos a las ocho. ¿Puedes llegar a esa hora?", "La ruta dura dos horas. ¿Qué vas a llevar?", "De momento somos cinco. ¿Quieres invitar a alguien más?"], "Perfecto. El viernes te confirmaré todos los detalles."),
    "A2 · Unidad 10: Culturas": _s("nueva vecina", "Ayudar a integrarse en el barrio", "Acabo de llegar al barrio. ¿Qué costumbre debería conocer?", ["¿Cómo puedo presentarme a los vecinos?", "¿A quién puedo pedir ayuda si tengo un problema?", "¿Qué actividad comunitaria me recomiendas?"], "Gracias por ayudarme a entender mejor la vida del barrio."),
    "Mensajes con intención": _s("recepcionista", "Dejar un mensaje profesional", "Buenos días. La persona que busca no está. ¿Quiere dejarle un mensaje?", ["¿Puede decirme el motivo de la llamada?", "¿Necesita que le devuelva la llamada hoy?", "¿Qué número o correo debo anotar?"], "De acuerdo. Le enviaré el mensaje y quedamos a la espera de su respuesta."),
    "B1 · Unidad 1: Volver a vernos": _s("antigua amiga", "Ponerse al día después de años", "¡Cuánto tiempo! ¿Qué ha sido de ti desde la última vez?", ["¿Cuál ha sido el cambio más importante en tu vida?", "¿Sigues en contacto con nuestros antiguos compañeros?", "¿Qué te parece si organizamos un reencuentro?"], "Me ha encantado ponerme al día contigo. No perdamos otra vez el contacto."),
    "B1 · Unidad 2: Recuerdos": _s("amiga de la infancia", "Contar una anécdota", "¿Cuál es uno de tus mejores recuerdos de infancia?", ["¿Cómo era el lugar y quién estaba contigo?", "¿Ocurrió algo inesperado aquel día?", "¿Cómo terminó la historia y por qué la recuerdas?"], "Qué historia tan especial. Se nota que ese momento quedó grabado en tu memoria."),
    "B1 · Unidad 3: El mundo del futuro": _s("periodista", "Debatir predicciones", "¿Cómo crees que serán nuestras ciudades en veinte años?", ["¿Qué papel tendrá la tecnología en esos cambios?", "¿Qué predicción te parece poco probable?", "¿Qué cambio deseas que ocurra y por qué?"], "Gracias por compartir tu visión del futuro con nuestros oyentes."),
    "B1 · Unidad 4: Trabajo": _s("entrevistadora", "Hacer una entrevista laboral", "Hábleme brevemente de su experiencia profesional.", ["¿Qué puede aportar a nuestro equipo?", "Cuénteme una situación difícil que haya resuelto.", "¿Por qué le interesa este puesto y qué condiciones valora?"], "Muchas gracias. Nos pondremos en contacto con usted después de las entrevistas."),
    "B1 · Unidad 5: Buen viaje": _s("agente de la aerolínea", "Reclamar por un vuelo perdido", "Buenos días. Explíqueme qué incidencia ha tenido.", ["¿Cuándo descubrió que había cambiado la puerta?", "Podemos ofrecerle hotel u otro vuelo. ¿Qué solución prefiere?", "¿Desea presentar además una reclamación formal?"], "He registrado la incidencia y la solución elegida. Lamentamos las molestias."),
    "B1 · Unidad 6: Vivienda": _s("representante municipal", "Proponer mejoras para el barrio", "Estamos recogiendo propuestas. ¿Qué problema del barrio considera prioritario?", ["¿Cómo afecta ese problema a los vecinos?", "¿Qué solución concreta propone al ayuntamiento?", "Si hubiera presupuesto, ¿qué otra mejora realizaría?"], "Incluiremos sus propuestas en la próxima reunión vecinal."),
    "B1 · Unidad 7: Relaciones humanas": _s("amiga", "Resolver un desacuerdo", "Noto que estás molesto. ¿Qué ha ocurrido?", ["¿Qué comportamiento te ha molestado exactamente?", "¿Has intentado ponerte en el lugar de la otra persona?", "¿Qué podríais hacer para llegar a un acuerdo?"], "Creo que hablar con sinceridad os ayudará a resolver el conflicto."),
    "B1 · Unidad 8: ¡Que aproveche!": _s("chef", "Explicar una receta", "Bienvenido a mi cocina. ¿Qué plato te gustaría preparar?", ["¿Qué ingredientes necesitas y cómo los vas a mezclar?", "¿Qué truco usarás para mejorar el sabor?", "¿Cómo debe servirse el plato y por qué?"], "La receta está lista y en su punto. ¡Que aproveche!"),
    "B1 · Unidad 9: Economía y consumo": _s("asesora de consumo", "Revisar hábitos de gasto", "¿En qué tipo de compras gastas más de lo que te gustaría?", ["¿Sueles comparar precios o compras por impulso?", "¿Qué productos podrías reparar en lugar de sustituir?", "¿Qué cambio harás este mes para ahorrar y consumir mejor?"], "Has creado un plan realista para controlar gastos y consumir de forma responsable."),
}
