"""DELE-style audio scripts for the listening exercise of every unit.

Each script is a short announcement, message, or mini-dialogue at the unit's
CEFR level. The TTS speaks the script (not the answer), and the question checks
real comprehension of what was heard — like a DELE comprensión auditiva tarea.
"""

from typing import Any

# title -> spoken text that makes the lesson's listening question(s) answerable
LISTENING_SCRIPTS: dict[str, str] = {
    # --- A1 ---
    "En el café": "—Buenos días, un café con leche y una tostada, por favor. —Muy bien. Son cuatro euros con cincuenta. —Aquí tiene. —Gracias, ahora se lo traigo todo a la mesa.",
    "Primeras presentaciones": "Hola, me llamo Ana. Soy de México, pero ahora vivo en Valencia con mi familia. Trabajo en una escuela de idiomas y me gusta mucho esta ciudad.",
    "Mi familia y mi casa": "Nuestra casa no es grande, pero es muy cómoda. Tiene dos dormitorios, un salón luminoso y una cocina pequeña. Vivimos cuatro personas y un gato.",
    "Un día normal": "Todos los días me levanto a las siete, desayuno rápido y salgo de casa a las ocho menos cuarto. El autobús pasa a las ocho en punto, así que no puedo llegar tarde.",
    "En la consulta": "—Me duele la garganta desde ayer y tengo un poco de fiebre. —No es nada grave. Debe descansar y beber mucha agua. Y esta semana no haga ejercicio ni vaya a trabajar.",
    "Compras en el mercado": "—¿Cuánto cuestan los tomates? —Hoy están baratos: dos euros el kilo. —Pues un kilo, por favor. —¿Algo más? —No, gracias, eso es todo.",
    "Aprender juntos": "Esta persona aprende español porque quiere viajar por Sudamérica. Estudia vocabulario cada día con una aplicación y los lunes practica con un grupo online.",
    "A1 · Unidad 6: Esto me gusta": "—¿Qué película quieres ver esta noche? —No sé... no me gustan nada las películas de terror. —¿Y una comedia? —¡Sí, perfecto! Me encantan las comedias.",
    "A1 · Unidad 7: De aquí para allá": "—Perdone, ¿dónde está la estación? —Muy cerca: está al lado del mercado, a dos minutos andando. —¿Al lado del parque? —No, al lado del mercado.",
    "A1 · Unidad 8: ¿Qué hacemos?": "—¿Quedamos a las siete? —No puedo, trabajo hasta las siete y media. Mejor a las ocho. —Vale, a las ocho en la plaza. —Perfecto.",
    "A1 · Unidad 9: Tiempo y ropa": "—Qué frío hace hoy. ¿Qué abrigo me pongo, el negro o el azul? —El azul te queda muy bien. —Vale, pues el azul, y las botas marrones.",
    "A1 · Unidad 10: Ciudadanos del mundo": "—¿Has viajado alguna vez a Colombia? —Sí, dos veces. Allí aprendí a cocinar arepas. —¿Arepas? Qué interesante. Yo solo sé hacer paella.",
    # --- A2 ---
    "Charla con vecinos": "Lucía está muy contenta: este fin de semana irá a la playa con su familia y no tendrá que trabajar en casa. Además, los vecinos han decidido cenar en el restaurante nuevo el viernes por la noche. Todos están invitados.",
    "De viaje": "—Perdone, ¿cómo llego a la estación? —Siga todo recto y luego gire a la izquierda en el semáforo. —¿A la izquierda? —Sí, a la izquierda. La verá enseguida, junto a la farmacia.",
    "Buscar piso": "—El piso tiene dos dormitorios, ascensor y mucha luz. —¿Y cuánto cuesta? —Novecientos euros al mes, con los gastos incluidos. —De acuerdo, ¿puedo visitarlo mañana?",
    "Vitamina A2 · U1: Vamos a conocernos": "Leo estudia español desde hace un año. Escribe correos muy bien y lee novelas sin problema, pero le cuesta entender las conversaciones rápidas de sus compañeros de clase.",
    "Vitamina A2 · U2: Mi lugar en el mundo": "Si pudiera elegir, viviría en un pueblo tranquilo cerca del mar. El centro de una gran ciudad es demasiado ruidoso para mí, aunque tiene más servicios y más tiendas.",
    "Vitamina A2 · Repaso U1–U2": "Para mejorar la comprensión, Clara escucha diálogos cortos todos los días. Todavía no lee novelas largas, porque prefiere practicar el oído con audios breves.",
    "Una ruta de senderismo": "Atención, grupo: la ruta de mañana dura dos horas por el bosque. No hace falta maleta ni ordenador, pero deben llevar agua y calzado cómodo. Quedamos a primera hora.",
    "A2 · Unidad 10: Culturas": "Cuando llegué al barrio no conocía a nadie. Los vecinos me han ayudado mucho: me han explicado las costumbres, me han invitado a sus fiestas y ahora me siento en casa.",
    # --- B1 ---
    "Mensajes con intención": "Primer mensaje: «Hola, soy Marta de la imprenta. ¿Puedes enviarme la factura del mes pasado? La necesito para la contabilidad. Si puedes, adjúntala hoy. Muchas gracias.»",
    "B1 · Unidad 1: Volver a vernos": "—¡Cuánto tiempo! ¿Qué ha sido de ti? —Pues mira, he cambiado de trabajo: ahora trabajo desde casa. —¡Qué bien! ¿Y sigues hablando inglés? —Claro, el idioma no ha cambiado.",
    "B1 · Unidad 2: Recuerdos": "Cuando era pequeño, un día perdí las llaves mientras volvía a casa. Estaba lloviendo y no llevaba teléfono. Al final, una vecina llamó a mis padres y todo se arregló.",
    "B1 · Unidad 3: El mundo del futuro": "Según los expertos, dentro de veinte años las ciudades serán más verdes y usaremos menos coches privados. También habrá más parques públicos y la energía limpia será más barata.",
    "B1 · Unidad 4: Trabajo": "—¿Te interesa el puesto? —Mucho. El horario es flexible y solo hay reuniones presenciales dos días por semana. —¿Y el sueldo? —Normal, pero prefiero la flexibilidad.",
    "B1 · Unidad 5: Buen viaje": "Cuando llegamos al aeropuerto, el vuelo ya había salido. En el mostrador, la compañía nos ofreció un hotel para pasar la noche y otro vuelo a la mañana siguiente. No nos dieron ningún reembolso.",
    "B1 · Unidad 6: Vivienda": "En la reunión vecinal todos coinciden: hace falta mejorar el transporte nocturno. Los alquileres y la biblioteca pueden esperar, pero los autobuses de noche son prioritarios para el barrio.",
    "B1 · Unidad 7: Relaciones humanas": "—¿Qué te pasa? —Me molesta que algunas personas interrumpan siempre cuando hablo. —Entiendo. ¿Has hablado con ellas? —Sí, y prefiero que lo resolvamos con calma.",
    "B1 · Unidad 8: ¡Que aproveche!": "La salsa lleva especias que hacen que el sabor sea más intenso. Y recuerda: sírvela fría para conservar mejor el aroma. Nunca la sirvas caliente ni congelada.",
    "B1 · Unidad 9: Economía y consumo": "Según la encuesta, la mayoría de las familias intenta reducir sus gastos, pero uno de cada tres consumidores compra por impulso. Además, casi nadie repara todo lo que se estropea.",
    # --- B2 ---
    "B2 · Unidad 1: Señas de identidad": "Mi nombre tiene una historia: me lo pusieron por mi bisabuela paterna, una mujer muy querida en la familia. No tiene nada que ver con ninguna marca, aunque mi apellido coincide con una muy famosa.",
    "B2 · Unidad 2: Enigmas": "El misterio ocurrió en un faro de la costa. Una noche de tormenta, los tres vigilantes desaparecieron sin dejar rastro, y ni el barco cercano ni el museo del puerto aportaron pistas.",
    "B2 · Unidad 3: Al límite": "—¿Qué se siente al saltar en paracaídas? —Una mezcla de miedo y euforia. No es calma, desde luego, pero tampoco arrepentimiento. Si tuviera la oportunidad, repetiría mañana mismo.",
    "B2 · Unidad 4: Referentes": "Mi profesora de literatura fue quien me animó a escribir mis primeros relatos. Nunca me habló de viajar lejos ni de cambiar de carrera: simplemente me enseñó a escribir con valentía.",
    "B2 · Unidad 5: Evolución": "La novela me gustó mucho: el estilo es cuidado y la portada es preciosa. Lo único que me decepcionó un poco fue el final, demasiado lento para mi gusto.",
    "B2 · Unidad 6: El paso del tiempo": "Queríamos restaurar el reloj antiguo de la plaza, pero costaba demasiado dinero. No estaba perdido ni era nuevo: simplemente no había presupuesto suficiente.",
    "B2 · Unidad 7: Suerte": "Soy un poco supersticioso: cuando encuentre un trébol de cuatro hojas, lo guardaré para siempre. Las monedas antiguas y las herraduras, la verdad, no me dicen nada.",
    "B2 · Unidad 8: Con duende": "Cada verano, el pueblo celebra un rito antiguo junto a la hoguera. No es un mercado ni una carrera: es una tradición llena de encanto que atrae a cientos de visitantes.",
    "B2 · Unidad 9: Con sentido": "De todos los sentidos, el mío predominante es el oído: recuerdo todas las voces y las canciones de mi infancia. La vista y el olfato me ayudan mucho menos.",
    "B2 · Unidad 10: Historia": "El puente fue construido en el siglo XIX y todavía sigue en pie. No es del siglo XXI ni del año pasado, aunque lo restauraron hace muy poco.",
    "B2 · Unidad 11: La imagen": "Aquel hombretón, con sus dos metros y sus manos enormes, resultó ser la persona más dulce del barrio. Parecía serio y tímido, pero siempre estaba dispuesto a ayudar.",
    "B2 · Unidad 12: Más que palabras": "—El café está frío. —Normal: lo pediste hace media hora y no lo has tocado. —Es verdad. Pues pídeme otro, por favor, y esta vez me lo tomo enseguida.",
    # --- C1 ---
    "C1 · Unidad 1: Individuo": "Si me preguntan quién soy, tardo en responder, porque uno no es solo su profesión ni su lugar de nacimiento. Me considero, ante todo, una persona hecha de contradicciones: me encanta la gente, aunque necesito largas horas de soledad; soy disciplinado en el trabajo y, sin embargo, un desastre con las plantas del balcón. No creo que la identidad sea algo fijo, como un documento, sino más bien un borrador que corregimos toda la vida. Lo que sí tengo claro es que los demás nos moldean: mi abuela me enseñó la paciencia y mis amigos, a reírme de mí mismo. No soy, desde luego, ni el superhéroe que imaginaba de niño ni el desastre que temía ser de adolescente.",
    "C1 · Unidad 2: Tiempo libre": "—¿Cómo aprovecha su tiempo libre? —Pues mire, antes pensaba que descansar era no hacer nada, pero con los años he aprendido que el verdadero descanso es cambiar de actividad. Los sábados salgo en bicicleta por la sierra y los domingos cocino con calma, algo impensable entre semana. —¿Y la televisión? —Apenas la enciendo; prefiero un buen libro o quedar con amigos. Eso sí, no soporto esas agendas de ocio que convierten el fin de semana en una maratón de planes. El tiempo libre, a fin de cuentas, debería saber a libertad, no a obligación disfrazada.",
    "C1 · Unidad 3: Mundo laboral": "—Lleva veinte años dirigiendo equipos. ¿Qué ha cambiado? —Casi todo, salvo lo esencial: las personas quieren sentirse valoradas. La tecnología ha transformado la oficina, desde luego; ahora trabajamos desde casa dos días por semana y las reuniones son por videollamada. Además, el teletrabajo nos ha obligado a medir los resultados y no las horas de presencia. No obstante, sigo creyendo que la confianza se construye cara a cara. —¿Y los jóvenes? —Tienen mucha razón en una cosa: no aceptan que el trabajo lo invada todo. En mi época presumíamos de hacer horas extras; hoy, afortunadamente, presumir de eso suena a fracaso, no a mérito.",
    "C1 · Unidad 4: Experiencia gastronómica": "En este restaurante de un pueblo de la costa no hay carta: el menú lo dicta el mercado cada mañana. La chef explica que su cocina parte de la memoria: «Recupero los guisos de mi abuela, aunque con técnicas actuales». Lo más sorprendente no es el sabor, sino el ritmo: aquí nadie tiene prisa y la sobremesa dura tanto como la comida. Los comensales, muchos venidos de la capital, admiten que lo que buscan no es lujo, sino autenticidad. Eso sí, el éxito tiene su precio: para reservar mesa un sábado hay que hacerlo con un mes de antelación.",
    "C1 · Unidad 5: Alternativas ambientales": "—El consumidor no puede con todo; la responsabilidad es de las grandes empresas. —De acuerdo en parte, pero si nadie compra ciertos productos, las empresas cambian. —Ya, pero pedirle a una familia que pague más por lo ecológico es injusto cuando llega a fin de mes con lo justo. —Por eso insisto en que hacen falta incentivos públicos: ayudas al transporte eléctrico, tasas a los envases de un solo uso... —¿Y mientras tanto? —Mientras tanto, pequeños gestos: reparar antes que tirar, comprar de temporada... No salvan el planeta por sí solos, pero tampoco son inútiles, como algunos sostienen con demasiada comodidad.",
    "C1 · Unidad 6: Educación": "—Los exámenes miden la memoria, no el talento. Habría que suprimirlos. —Suprimirlos me parece exagerado; reformarlos, desde luego. El problema no es evaluar, sino evaluar solo con un examen final. —Exacto: proyectos, trabajo en equipo, portafolios... cualquier instrumento que muestre el proceso y no únicamente el resultado. —Siempre que haya criterios claros, porque la evaluación continua también puede generar ansiedad si se convierte en un examen permanente. —En eso tiene razón. —Además, no olvidemos al profesorado: sin formación, sin tiempo y sin recursos, cualquier reforma, por brillante que parezca, se queda en papel mojado.",
    "C1 · Unidad 7: Paisajes urbanos": "El barrio ha cambiado tanto que quien se fue hace diez años apenas lo reconocería. Donde había solares abandonados hoy hay huertos urbanos y un centro cultural; las aceras se han ensanchado y los coches han cedido espacio a las bicicletas. No todo el mundo celebra la transformación: algunos vecinos temen que la llegada de cafeterías modernas encarezca los alquileres y expulse a los de siempre. El ayuntamiento asegura que protegerá a los comercios tradicionales, aunque los vecinos recuerdan que promesas parecidas se quedaron en nada en otros distritos. El futuro del barrio, de momento, es una obra en construcción.",
    "C1 · Unidad 8: Geografías y viajes": "—Ha recorrido medio mundo. ¿Qué viaje le marcó? —Curiosamente, uno de los más cortos: una semana en el desierto. Aprendí que viajar despacio cambia la mirada; no es lo mismo tachar países de una lista que dejarse atravesar por un lugar. —¿Algún consejo? —Sí: aprender unas palabras del idioma local y soltar el móvil de vez en cuando. Los mapas están muy bien, pero perderse también enseña. —¿Y el turismo masivo? —Es la gran contradicción: viajamos buscando lo auténtico y, al llegar todos a la vez, lo borramos. Quizá el viajero más respetuoso sea el que sabe cuándo no ir.",
    "C1 · Unidad 9: Deporte y bienestar": "—Empezó a correr a los cincuenta. ¿Por qué? —Porque el médico me dio un susto, la verdad. Al principio no aguantaba ni diez minutos; ahora corro tres veces por semana y duermo como hacía años que no dormía. —¿Y la alimentación? —Nada de dietas milagro: simplemente cocino más y picoteo menos. El secreto, si es que existe, es la constancia, no la intensidad. —¿Qué le diría a quien no encuentra tiempo? —Que el bienestar no es un lujo para cuando sobren horas, sino una inversión. Aunque, eso sí, tampoco hay que obsesionarse: el deporte debe sumar vida, no restarla.",
    "C1 · Unidad 10: Economía y negocios": "—Su empresa sobrevivió a la crisis. ¿Cuál fue la clave? —No endeudarnos más de la cuenta y cuidar al equipo cuando apretaban los tiempos. Muchos competidores recortaron personal y, cuando volvieron los pedidos, no tenían con quién responder. —¿Cómo ve la economía actual? —Con prudencia optimista, que diría un economista. La inflación se ha moderado, pero los costes energéticos siguen pesando. —¿Algún consejo para emprendedores? —Que hagan números pesimistas y sueños optimistas, en ese orden. Y que no confundan crecer rápido con crecer bien: lo primero impresiona en las noticias; lo segundo paga las nóminas.",
    "C1 · Unidad 11: Palabras, palabras": "Hay palabras que uno colecciona sin proponérselo. A mí me ocurre con «desvelado», que suena mucho más elegante de lo que siente quien no puede dormir, o con «alboroto», que parece escrita para las mañanas de los niños. Los idiomas, además, guardan tesoros intraducibles: el portugués tiene «saudade» y nosotros, la «sobremesa», ese rato en que ya no se come, pero nadie quiere levantarse. Me divierte comprobar cómo las palabras envejecen: las que usaban mis abuelos suenan hoy a museo, y las de mis sobrinos, a otro planeta. Sin embargo, todas cumplen lo esencial: tendernos un puente hacia los demás, aunque a veces el puente cruja.",
    "C1 · Unidad 12: Siglo XXI": "Vivimos, nos dicen, en la era de la información, y sin embargo nunca había sido tan difícil estar bien informado. Las noticias nos llegan al instante, pero también los bulos; tenemos el mundo en el bolsillo, aunque a veces apenas miramos más allá de la pantalla. El siglo XXI ha traído avances asombrosos: vacunas desarrolladas en meses, videollamadas con el otro lado del planeta, energías limpias cada vez más baratas. Pero también plantea preguntas incómodas sobre la privacidad, el trabajo que automatizan las máquinas y la soledad en medio de la hiperconexión. El futuro, en definitiva, ya no es algo que nos espera: es algo que estamos escribiendo, a veces sin releer lo que escribimos.",
    # --- C2 ---
    "C2 · Unidad 1: Retórica y debate": "Permítanme una observación previa: no es infrecuente que quien confunde el debate con la contienda termine ganando la discusión y perdiendo la razón. La retórica, lejos de ser el arte de embaucar —como con cierta ligereza se sostiene—, constituye la disciplina de ordenar el pensamiento para hacerlo audible. No cabe duda de que un argumento sólido puede enmarañarse en una mala exposición, del mismo modo que una falacia, bien vestida, desfila con aire de verdad. De ahí que la formación del ciudadano exija tanto la construcción de razonamientos como su disección: saber cuándo nos convencen y cuándo, sencillamente, nos envuelven. Quien solo sabe replicar no debate: hace ruido con bibliografía.",
    "C2 · Unidad 2: Lengua y sociedad": "Resulta cuando menos paradójico que la lengua, instrumento de encuentro, se esgrima con tanta frecuencia como frontera. Cada habla arrastra una historia social: quien corrige el acento ajeno rara vez persigue la claridad, sino más bien la delimitación de un nosotros y un ellos. No ignoro que la norma cumple una función cohesionadora; ahora bien, convertirla en vara de medir el valor de las personas constituye una deriva que la filología no avala y la cortesía desaconseja. Las lenguas, a fin de cuentas, no pertenecen a las academias ni a los ministerios: habitan en la boca de quien las usa, y es allí —y no en los despachos— donde deciden, tozudas, cómo quieren seguir siendo dichas.",
    "C2 · Unidad 3: Ciencia y divulgación": "—Se dedica a divulgar ciencia. ¿No teme simplificar en exceso? —El riesgo existe, desde luego, pero cabría preguntarse si la alternativa —un conocimiento custodiado por iniciados— resulta preferible. Simplificar no es traicionar, siempre que se declare dónde termina la metáfora y empieza el modelo. —¿Y la desinformación? —He aquí la paradoja: nunca hubo tanto dato disponible ni tanta resistencia a ponderarlo. El divulgador no compite con la ignorancia, sino con la certeza apresurada. —¿Una receta? —Humildad metodológica: decir «no lo sabemos todavía» no debilita la ciencia; la distingue del charlatanismo. Y conviene recordar que el escepticismo, mal administrado, deviene en lo contrario de lo que pretende.",
    "C2 · Unidad 4: Literatura": "—¿Para qué sirve la literatura? —La pregunta, con perdón, ya parte de un malentendido: exigirle utilidad a la novela es como pedirle rentabilidad a la amistad. La literatura no sirve; permanece. Nos presta ojos ajenos para mirar lo propio y nos enseña que la vida real, con su desorden, carece de la coherencia que exigimos a la ficción. —¿Y el escritor? —Un profesional de la sospecha: duda de la primera frase, de la segunda y, con suerte, publica la tercera. —¿Crisis de la lectura? —Llevamos siglos enterrando al libro y el muy obstinado sigue asistiendo a su propio funeral con tapas nuevas.",
    "C2 · Unidad 5: Medios y opinión": "—El periodismo de opinión ha devorado al de información. —La afirmación, aunque extendida, merece matices: la opinión siempre existió; lo nuevo es su velocidad y su monetización. —Me refería a la pérdida de rigor. —Que la hay, pero convendría precisar responsabilidades: el medio que confunde el titular con el cebo no lo hace por ignorancia, sino por modelo de negocio. —¿Y el lector? —No es una víctima pasiva, aunque tampoco un consumidor omnisciente. Verificar exige tiempo, y el tiempo, esa materia prima, es justo lo que el sistema le disputa. —¿Solución? —Educación mediática, suscripciones que financien el trabajo lento y, por qué no, la sana costumbre de no compartir lo que no hemos terminado de leer.",
    "C2 · Unidad 6: Memoria histórica": "Toda sociedad administra su pasado con una mezcla de memoria y de estratégico olvido, y sería ingenuo suponer que la nuestra constituye una excepción. La memoria histórica no persiste en reabrir heridas, como a veces se objeta con notable interés, sino en impedir que las heridas se administren sin testigos. El archivo, la fotografía, el testimonio del último superviviente: he ahí materiales que no piden venganza, sino exactitud. Cabe recordar, por lo demás, que el olvido rara vez es neutro: siempre olvida a los mismos. Honrar a las víctimas no compromete el presente con el rencor; lo compromete con la verdad, que es bien distinto y bastante más incómodo para quienes prefieren la historia en versión resumida.",
    "C2 · Unidad 7: Humor e ironía": "El humor, ese género menor según quienes nunca han conseguido hacer reír, constituye en realidad una forma superior de la inteligencia: exige detectar la costura del mundo y descoserla con elegancia. La ironía, su prima refinada, consiste en decir lo contrario confiando en que el oyente no sea exactamente lo contrario de un oyente atento. No faltan quienes la consideran un vicio británico importado, como si Cervantes hubiera escrito en Manchester. En España, por lo demás, practicamos la autocomplacencia con tal fervor que la sátira apenas logra ir por delante de la realidad: uno redacta un exabrupto y, antes de publicarlo, la vida ya lo ha superado. Reírse de uno mismo, eso sí, sigue siendo el único lujo verdaderamente democrático.",
    "C2 · Unidad 8: Lenguaje administrativo": "Cualquier ciudadano que se haya enfrentado a una notificación oficial conoce esa prosa en la que uno «comparece», «expone» y «solicita», pero jamás, por activa ni por pasiva, entiende. El lenguaje administrativo, concebido para garantizar la precisión jurídica, ha acabado garantizando sobre todo la distancia: quien redacta «a los efectos oportunos» rara vez se pregunta por los efectos en el lector. No se trata de suprimir la exactitud, obviamente, sino de reconocer que la claridad también es un derecho, y no el menor. Hay administraciones que ya publican guías de lenguaje claro; iniciativa loable que, a juzgar por los formularios, aún se encuentra en fase de tramitación, con la parsimonia que caracteriza al género.",
    "C2 · Unidad 9: Identidades": "—La identidad es un relato que nos contamos; nada hay de esencial en ella. —Concedo lo del relato, pero un relato compartido durante generaciones pesa más que una opinión. —¿Pesa o encadena? El problema surge cuando la identidad se administra como aduana: dentro, los auténticos; fuera, los sospechosos. —Nadie propone aduanas. —Se proponen sin proponerlas: en cada examen de pureza, en cada «usted no es de aquí». —Matizaría: también puede ser hogar, lengua de la infancia, memoria común. —Naturalmente; lo que objerto es su uso como arma arrojadiza. La identidad, bien entendida, debería funcionar como una casa con puerta, no como un búnker con bandera.",
    "C2 · Unidad 10: El siglo digital": "—Los algoritmos nos conocen mejor que nosotros mismos. —Afirmación discutible: nos predicen, que no es lo mismo. Confundir el patrón de clics con la intimidad revela una pobreza conceptual notable, aunque comercialmente muy rentable. —Acepto la puntualización; el caso es que decidimos menos de lo que creemos. —Siempre fue así: la novedad no es la influencia, sino su escala y su invisibilidad. —¿Regulación? —Imprescindible y tardía, como casi toda regulación tecnológica. El dilema es conocido: legislar despacio es llegar tarde; legislar deprisa, legislar mal. —¿Optimismo? —Cauto. La tecnología no nos salvará ni nos condenará; amplificará, simplemente, lo que ya somos. Resultado que, según el día, invita al entusiasmo o a la sobriedad.",
}


def enrich_listening(lessons: list[dict[str, Any]]) -> None:
    """Attach the DELE-style audio script to each lesson's listening exercises."""
    for lesson in lessons:
        script = LISTENING_SCRIPTS.get(lesson["title"])
        if not script:
            continue
        for exercise in lesson["exercises"]:
            if exercise["type"] == "listening" and exercise.get("audio"):
                exercise["audio_text"] = script
